# Variaveis interpoladas estão definidas no .env

services:
  db:
    image: postgres:17.5-alpine3.22
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DB_USER}
      POSTGRES_USER: ${POSTGRES_DB_PASS}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    healthcheck:
      test: pg_isready -U stone -d stone
      interval: 5s
      timeout: 2s
      retries: 10

  server:
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      db: 
        condition: service_healthy
    environment:
      POSTGRES_DB_HOST: db
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
      POSTGRES_DB_USER: ${POSTGRES_DB_USER}
      POSTGRES_DB_PASS: ${POSTGRES_DB_PASS}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
